### ISSUE TITLE
Potential dependency conflicts between allofplos and urllib3

### ISSUE THREAD

**Issue by NeolithEra** [PLOS/allofplos#127]
Hi, as shown in the following full dependency graph of  **_allofplos_**, **_agavepy_** requires **_urllib3 >=1.22_** ， while the installed version of **_requests _**(2.22.0) requires _**urllib3  <1.26,>=1.21.1**_.

According to Pip's _“first found wins”_ installation strategy, _**urllib3 1.25.7**_ is the actually installed version.  

Although the first found package version _**urllib3 1.25.7**_ just satisfies the later dependency constraint （_**urllib3  <1.26,>=1.21.1**_), it will lead to a build failure once developers release a newer version of **_urllib3_**.

### Dependency tree--------
```
allofplos - 0.12.0
| +- certifi(install version:2019.11.28 version range:>=2017.7.27.1)
| +- chardet(install version:3.0.4 version range:>=3.0.4)
| +- idna(install version:2.8 version range:>=2.6)
| +- lxml(install version:4.4.2 version range:>=4.0.0)
| +- peewee(install version:3.13.1 version range:>=3.5.2)
| +- python-utils(install version:2.3.0 version range:>=2.2.0)
| +- requests(install version:2.22.0 version range:>=2.18.4)
| | +- certifi(install version:2019.11.28 version range:>=2017.4.17)
| | +- chardet(install version:3.0.4 version range:<3.1.0,>=3.0.2)
| | +- idna(install version:2.8 version range:>=2.5,<2.9)
| | +- urllib3(install version:1.25.7 version range:<1.26,>=1.21.1)
| +- six(install version:1.13.0 version range:>=1.11.0)
| +- tqdm(install version:4.41.0 version range:>=4.17.1)
| +- unidecode(install version:1.1.1 version range:>=0.04.21)
| +- urllib3(install version:1.25.7 version range:>=1.22) 
```

Thanks for your attention.
Best,
Neolith

**Comment by NeolithEra** [comment]
### Suggested Solution

1.	Fix his direct dependencies to be **_urllib3  <1.26_**.
2.	Ask your upstream project **_request_** to losse the version range of **_urllib3_** to be **_>=1.21.1_**.

@eseiver Which solution do you prefer, 1 or 2?
Please let me know your choice. May I pull a request to solve this issue?

**Comment by egh** [comment]
Thank you! @NeolithEra Please do feel free to file a pull request to correct his issue.

**Comment by Syzygy2048** [comment]
I'm unable to follow the installation instructions due to version conflicts when running `pip install -r requirements.txt`

My modified requirements file is
```certifi==2017.7.27.1
chardet==3.0.4
idna==2.6
lxml==4.4.2
python-utils==2.2.0
requests==2.18.4
six==1.11.0
tqdm==4.17.1
unidecode==0.04.21
urllib3==1.22
peewee==2.10.2```
