### ISSUE TITLE
allofplos.update error

### ISSUE THREAD

**Issue by tweverett** [PLOS/allofplos#133]
I get the following error when I do a fresh install and then execute: 
(allofplos) PS C:\Users\teverett> python -m allofplos.update

Not enough articles in C:\Users\teverett\allofplos\lib\site-packages\allofplos\allofplos_xml, re-downloading zip file
Creating folder for article xml
Traceback (most recent call last):
  File "C:\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\teverett\allofplos\lib\site-packages\allofplos\update.py", line 52, in <module>
    main()
  File "C:\Users\teverett\allofplos\lib\site-packages\allofplos\update.py", line 25, in main
    create_local_plos_corpus()
  File "C:\Users\teverett\allofplos\lib\site-packages\allofplos\corpus\plos_corpus.py", line 592, in create_local_plos_corpus
    zip_date, zip_size, metadata_path = get_zip_metadata()
  File "C:\Users\teverett\allofplos\lib\site-packages\allofplos\corpus\gdrive.py", line 123, in get_zip_metadata
    zip_date = datetime.datetime.strptime(zip_datestring, time_formatting)
  File "C:\Python310\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Python310\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '' does not match format '%Y_%b_%d_%Hh%Mm%Ss'

**Comment by Syzygy2048** [comment]
I encountered the same issue.

Looking at the code, it seems like the metadata file holding information about the download has been removed or the permissions have changed?
See https://github.com/PLOS/allofplos/blob/85a8cdcf783a5cf36f94e7eb2083aa74430beb57/allofplos/corpus/gdrive.py#L13
For the id. The zip_datestring var as per L123 of your crash log should come from this file.

I was also able to download the plos zips directly from google drive with the ID stored in https://github.com/PLOS/allofplos/blob/85a8cdcf783a5cf36f94e7eb2083aa74430beb57/allofplos/corpus/gdrive.py#L12

Specifically with the url https://drive.google.com/uc?id=0B_JDnoghFeEKLTlJT09IckMwOFk&export=download

Although I haven't figured out if this is up to date or not. The file holding the ID was last updated early 2018, but the zip contains data with a publication dates from 2019 (but not 2020 or 2021).

**Comment by sbassi** [comment]
Maybe @eseiver can tell us about it, since she worked on the data side of this project.

**Comment by eseiver** [comment]
Not sure why the `datetime.strptime` time formatting in the error is `%Y%b%d%Hh%Mm%Ss`, because that doesn't match the code in the master branch: 
https://github.com/PLOS/allofplos/blob/a6bd47d150a87095c9ce741aa0cab108697c3e4d/allofplos/corpus/gdrive.py#L16
As for updating the zip file, I don't control the server that updates the metadata file and zip file since I haven't been at PLOS since 2018, @egh might know more about its status.

**Comment by egh** [comment]
I can reproduce locally. I'll look into it.

**Comment by egh** [comment]
https://support.google.com/a/answer/10685032?hl=en I think this is the issue

**Comment by egh** [comment]
I made a PR that should fix this. If you have a chance to try it out, I would appreciate it. Thanks!

**Comment by Syzygy2048** [comment]
With these changes I was able to run it.

I noticed that the allofplos_xml folder already had an invalid zip_info.txt file in it, presumably from earlier attempts. Deleting and rerunning solved it.

@egh I believe the readme currently only states how to run from the installed library, not the code and should be updated.

**Comment by egh** [comment]
@Syzygy2048 Thanks for checking!

Do these instructions not work for you?

https://github.com/plos/allofplos/blob/master/README.rst#installation-instructions

> If you want to manually install from source (for example for development purposes), first clone the project repository:

> (allofplos)$ git clone git@github.com:PLOS/allofplos.git

> Install Python dependencies inside the newly created virtual environment:

> (allofplos)$ pip install -r requirements.txt

**Comment by Syzygy2048** [comment]
The instructions work, it was a misunderstanding on my part.

@egh Just to double check, is the latest version supposed to be from Sept. 2019?

**Comment by egh** [comment]
> Just to double check, is the latest version supposed to be from Sept. 2019?

Not sure what you mean by "latest version". The latest version on pypi is from August 2019 - it needs an update.

**Comment by Syzygy2048** [comment]
Sorry, I could have been clearer on that.

The lastest version of the dataset is from 2019_Sep_30_16h00m59s ?

**Comment by egh** [comment]
Ah, I see. Yes, because of some problems we haven't updated a zip file. However, allofplos will download all the individual XML files to get you up-to-date when you run `python -m allofplos.update`.
