### ISSUE TITLE
Use git tags to designate releases on GitHub as well

### ISSUE THREAD

**Issue by mpacer** [PLOS/allofplos#24]
GitHub has a notion of releases that people (e.g., me) will sometimes go to when I want to look at the history of specific versions of the packages. 

You can access this feature (I believe) by giving a tag with a semver type version number to the PR that is equivalent to the release commit.

for example:

```
git checkout d732feb2
git tag 0.8.1
git push --tags
```

would create a tagged release attached to the code base at the commit with the [d732feb2](https://github.com/PLOS/allofplos/commit/d732feb2d7fc91c4048087b1330b194360d58824) hash (the merge commit for #21).

**Comment by sbassi** [comment]
Thank you. Done.
