### ISSUE TITLE
Change file naming convention for PLOS 'annotation' DOIs

### ISSUE THREAD

**Issue by eseiver** [PLOS/allofplos#28]
Right now the doi_to_path() etc transformations require XML parsing for annotation DOIs to get the journal name. Need to change this so that the transformations don't rely on anything outside of the DOI string.

**Comment by eseiver** [comment]
Working on this in https://github.com/PLOS/allofplos/tree/annotations

**Comment by mpacer** [comment]
This was merged, if you include the words "closes #28" in the pr notes or commit message, it will automatically close the issue when merged.

**Comment by eseiver** [comment]
Oh that is clever! Thanks @mpacer 
closes #28.
