### ISSUE TITLE
Cannot get corpus dir

### ISSUE THREAD

**Issue by egh** [PLOS/allofplos#85]
According to the README, I can get the corpus dir. But when I run the recommended command, I get an error

```
λ python -c "from allofplos.plos_regex import corpusdir; print(corpusdir)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'corpusdir'
```

Environment:

```
λ python --version
Python 3.5.2
λ pip freeze
allofplos==0.10.2
certifi==2018.1.18
chardet==3.0.4
idna==2.6
lxml==4.1.1
peewee==3.1.0
pkg-resources==0.0.0
python-utils==2.3.0
requests==2.18.4
six==1.11.0
tqdm==4.19.5
Unidecode==1.0.22
urllib3==1.22
```

**Comment by sbassi** [comment]
Most likely the doc is outdated, here is how I do it:

python -c "from allofplos.plos_regex import get_corpus_dir; print(get_corpus_dir())"
/home/sbassi/projects/plos/sbrepo/allofplos/allofplos/allofplos_xml

**Comment by sbassi** [comment]
will make a branch for the doc update.

**Comment by egh** [comment]
:+1: Thanks @sbassi !!

**Comment by egh** [comment]
Your version works great for me:
```
λ python -c "from allofplos.plos_regex import get_corpus_dir; print(get_corpus_dir())"
/home/egh/.virtualenvs/allofplos2/local/lib/python3.5/site-packages/allofplos/allofplos_xml
```

**Comment by mpacer** [comment]
I'd like to point out that you could do

`python -c "from allofplos import get_corpus_dir; print(get_corpus_dir())"`

since it's contained at the top level allofplos/__init__.py

**Comment by mpacer** [comment]
I'd like to point out that you could do

```
python -c "from allofplos import get_corpus_dir; print(get_corpus_dir())"
```

since it's contained at the top level allofplos/__init__.py

**Comment by sbassi** [comment]
labeled as a bug because it is a documentation bug
