### ISSUE TITLE
Update broken b/c related-doi

### ISSUE THREAD

**Issue by eseiver** [PLOS/allofplos#99]
The latest PLOS corpus update didn't work because it couldn't parse the related DOI from the recent retraction pone.0194455.  Will probably need to issue a patch.

**Comment by egh** [comment]
I was just going to report this. Thanks! :smile:

**Comment by eseiver** [comment]
they will be issuing a repub, but problem still remains of how to handle XML files that don't work correctly. right now, the script stops entirely, all articles already downloaded to new articles by default stay there and aren't redownloaded when the script is re-run. we should prevent the download in the first place, and just try the download again every time the script runs.
